require: rubocop-rubycw
AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  Exclude:
    - 'vendor/bundle/**/*'
Rubycw/Rubycw:
  Enabled: true
  Exclude:
    - 'test/**/*_test.rb'

Lint/DuplicateMethods:
  Enabled: true
  Include:
    - 'test/**/*_test.rb'
