require: rubocop-rubycw
AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  Exclude:
    - 'test/**/*_test.rb'
    - 'vendor/bundle/**/*'
    - lib/ruby/signature/parser.rb
Rubycw/Rubycw:
  Enabled: true
