name: RBS Comments

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    container:
      image: rubylang/ruby:3.1-focal
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libdb-dev
    - name: Update rubygems & bundler
      run: |
        ruby -v
        gem update --system
    - name: bundle config set with
      run: |
        echo "NO_MINITEST=true" >> $GITHUB_ENV
        bundle config set --local without 'minitest'
      if: "contains(matrix.container_tag, 'master-nightly')"
    - name: bin/setup
      run: |
        bin/setup
    - name: Run test
      run: |
        bundle exec rake annotate confirm_annotation
